module KeyValues

  class Base < ActiveHash::Base
    def self.find_by_code(code)
      super(code.to_s)
    end

    def self.codes
      self.all.map(&:code)
    end
  end

  class PokeInfo < KeyValues::Base
    self.data = [
      { code: :MISSINGNO, id: 0 },
      { code: :BULBASAUR, id: 1, tw_name: "妙蛙種子", jp_name: "フシギダネ", en_name: "Bulbasaur" },
      { code: :IVYSAUR, id: 2, tw_name: "妙蛙草", jp_name: "フシギソウ", en_name: "Ivysaur" },
      { code: :VENUSAUR, id: 3, tw_name: "妙蛙花", jp_name: "フシギバナ", en_name: "Venusaur" },
      { code: :CHARMANDER, id: 4, tw_name: "小火龍", jp_name: "ヒトカゲ", en_name: "Charmander" },
      { code: :CHARMELEON, id: 5, tw_name: "火恐龍", jp_name: "リザード", en_name: "Charmeleon" },
      { code: :CHARIZARD, id: 6, tw_name: "噴火龍", jp_name: "リザードン", en_name: "Charizard" },
      { code: :SQUIRTLE, id: 7, tw_name: "傑尼龜", jp_name: "ゼニガメ", en_name: "Squirtle" },
      { code: :WARTORTLE, id: 8, tw_name: "卡咪龜", jp_name: "カメール", en_name: "Wartortle" },
      { code: :BLASTOISE, id: 9, tw_name: "水箭龜", jp_name: "カメックス", en_name: "Blastoise" },
      { code: :CATERPIE, id: 10, tw_name: "綠毛蟲", jp_name: "キャタピー", en_name: "Caterpie" },
      { code: :METAPOD, id: 11, tw_name: "鐵甲蛹", jp_name: "トランセル", en_name: "Metapod" },
      { code: :BUTTERFREE, id: 12, tw_name: "巴大蝶", jp_name: "バタフリー", en_name: "Butterfree" },
      { code: :WEEDLE, id: 13, tw_name: "獨角蟲", jp_name: "ビードル", en_name: "Weedle" },
      { code: :KAKUNA, id: 14, tw_name: "鐵殼昆", jp_name: "コクーン", en_name: "Kakuna" },
      { code: :BEEDRILL, id: 15, tw_name: "大針蜂", jp_name: "スピアー", en_name: "Beedrill" },
      { code: :PIDGEY, id: 16, tw_name: "波波", jp_name: "ポッポ", en_name: "Pidgey" },
      { code: :PIDGEOTTO, id: 17, tw_name: "比比鳥", jp_name: "ピジョン", en_name: "Pidgeotto" },
      { code: :PIDGEOT, id: 18, tw_name: "比雕", jp_name: "ピジョット", en_name: "Pidgeot" },
      { code: :RATTATA, id: 19, tw_name: "小拉達", jp_name: "コラッタ", en_name: "Rattata" },
      { code: :RATICATE, id: 20, tw_name: "拉達", jp_name: "ラッタ", en_name: "Raticate" },
      { code: :SPEAROW, id: 21, tw_name: "烈雀", jp_name: "オニスズメ", en_name: "Spearow" },
      { code: :FEAROW, id: 22, tw_name: "大嘴雀", jp_name: "オニドリル", en_name: "Fearow" },
      { code: :EKANS, id: 23, tw_name: "阿柏蛇", jp_name: "アーボ", en_name: "Ekans" },
      { code: :ARBOK, id: 24, tw_name: "阿柏怪", jp_name: "アーボック", en_name: "Arbok" },
      { code: :PIKACHU, id: 25, tw_name: "皮卡丘", jp_name: "ピカチュウ", en_name: "Pikachu" },
      { code: :RAICHU, id: 26, tw_name: "雷丘", jp_name: "ライチュウ", en_name: "Raichu" },
      { code: :SANDSHREW, id: 27, tw_name: "穿山鼠", jp_name: "サンド", en_name: "Sandshrew" },
      { code: :SANDSLASH, id: 28, tw_name: "穿山王", jp_name: "サンドパン", en_name: "Sandslash" },
      { code: :NIDORAN_FEMALE, id: 29, tw_name: "尼多蘭", jp_name: "ニドラン♀", en_name: "Nidoran♀" },
      { code: :NIDORINA, id: 30, tw_name: "尼多娜", jp_name: "ニドリーナ", en_name: "Nidorina" },
      { code: :NIDOQUEEN, id: 31, tw_name: "尼多后", jp_name: "ニドクイン", en_name: "Nidoqueen" },
      { code: :NIDORAN_MALE, id: 32, tw_name: "尼多朗", jp_name: "ニドラン♂", en_name: "Nidoran♂" },
      { code: :NIDORINO, id: 33, tw_name: "尼多力諾", jp_name: "ニドリーノ", en_name: "Nidorino" },
      { code: :NIDOKING, id: 34, tw_name: "尼多王", jp_name: "ニドキング", en_name: "Nidoking" },
      { code: :CLEFAIRY, id: 35, tw_name: "皮皮", jp_name: "ピッピ", en_name: "Clefairy" },
      { code: :CLEFABLE, id: 36, tw_name: "皮可西", jp_name: "ピクシー", en_name: "Clefable" },
      { code: :VULPIX, id: 37, tw_name: "六尾", jp_name: "ロコン", en_name: "Vulpix" },
      { code: :NINETALES, id: 38, tw_name: "九尾", jp_name: "キュウコン", en_name: "Ninetales" },
      { code: :JIGGLYPUFF, id: 39, tw_name: "胖丁", jp_name: "プリン", en_name: "Jigglypuff" },
      { code: :WIGGLYTUFF, id: 40, tw_name: "胖可丁", jp_name: "プクリン", en_name: "Wigglytuff" },
      { code: :ZUBAT, id: 41, tw_name: "超音蝠", jp_name: "ズバット", en_name: "Zubat" },
      { code: :GOLBAT, id: 42, tw_name: "大嘴蝠", jp_name: "ゴルバット", en_name: "Golbat" },
      { code: :ODDISH, id: 43, tw_name: "走路草", jp_name: "ナゾノクサ", en_name: "Oddish" },
      { code: :GLOOM, id: 44, tw_name: "臭臭花", jp_name: "クサイハナ", en_name: "Gloom" },
      { code: :VILEPLUME, id: 45, tw_name: "霸王花", jp_name: "ラフレシア", en_name: "Vileplume" },
      { code: :PARAS, id: 46, tw_name: "派拉斯", jp_name: "パラス", en_name: "Paras" },
      { code: :PARASECT, id: 47, tw_name: "派拉斯特", jp_name: "パラセクト", en_name: "Parasect" },
      { code: :VENONAT, id: 48, tw_name: "毛球", jp_name: "コンパン", en_name: "Venonat" },
      { code: :VENOMOTH, id: 49, tw_name: "末入蛾", jp_name: "モルフォン", en_name: "Venomoth" },
      { code: :DIGLETT, id: 50, tw_name: "地鼠", jp_name: "ディグダ", en_name: "Diglett" },
      { code: :DUGTRIO, id: 51, tw_name: "三地鼠", jp_name: "ダグトリオ", en_name: "Dugtrio" },
      { code: :MEOWTH, id: 52, tw_name: "喵喵", jp_name: "ニャース", en_name: "Meowth" },
      { code: :PERSIAN, id: 53, tw_name: "貓老大", jp_name: "ペルシアン", en_name: "Persian" },
      { code: :PSYDUCK, id: 54, tw_name: "可達鴨", jp_name: "コダック", en_name: "Psyduck" },
      { code: :GOLDUCK, id: 55, tw_name: "哥達鴨", jp_name: "ゴルダック", en_name: "Golduck" },
      { code: :MANKEY, id: 56, tw_name: "猴怪", jp_name: "マンキー", en_name: "Mankey" },
      { code: :PRIMEAPE, id: 57, tw_name: "火爆猴", jp_name: "オコリザル", en_name: "Primeape" },
      { code: :GROWLITHE, id: 58, tw_name: "卡蒂狗", jp_name: "ガーディ", en_name: "Growlithe" },
      { code: :ARCANINE, id: 59, tw_name: "風速狗", jp_name: "ウインディ", en_name: "Arcanine" },
      { code: :POLIWAG, id: 60, tw_name: "蚊香蝌蚪", jp_name: "ニョロモ", en_name: "Poliwag" },
      { code: :POLIWHIRL, id: 61, tw_name: "蚊香蛙", jp_name: "ニョロゾ", en_name: "Poliwhirl" },
      { code: :POLIWRATH, id: 62, tw_name: "快泳蛙", jp_name: "ニョロボン", en_name: "Poliwrath" },
      { code: :ABRA, id: 63, tw_name: "凱西", jp_name: "ケーシィ", en_name: "Abra" },
      { code: :KADABRA, id: 64, tw_name: "勇基拉", jp_name: "ユンゲラー", en_name: "Kadabra" },
      { code: :ALAKAZAM, id: 65, tw_name: "胡地", jp_name: "フーディン", en_name: "Alakazam" },
      { code: :MACHOP, id: 66, tw_name: "腕力", jp_name: "ワンリキー", en_name: "Machop" },
      { code: :MACHOKE, id: 67, tw_name: "豪力", jp_name: "ゴーリキー", en_name: "Machoke" },
      { code: :MACHAMP, id: 68, tw_name: "怪力", jp_name: "カイリキー", en_name: "Machamp" },
      { code: :BELLSPROUT, id: 69, tw_name: "喇叭芽", jp_name: "マダツボミ", en_name: "Bellsprout" },
      { code: :WEEPINBELL, id: 70, tw_name: "喇叭花", jp_name: "ウツドン", en_name: "Weepinbell" },
      { code: :VICTREEBEL, id: 71, tw_name: "大食花", jp_name: "ウツボット", en_name: "Victreebel" },
      { code: :TENTACOOL, id: 72, tw_name: "瑪瑙水母", jp_name: "メノクラゲ", en_name: "Tentacool" },
      { code: :TENTACRUEL, id: 73, tw_name: "毒刺水母", jp_name: "ドククラゲ", en_name: "Tentacruel" },
      { code: :GEODUDE, id: 74, tw_name: "小拳石", jp_name: "イシツブテ", en_name: "Geodude" },
      { code: :GRAVELER, id: 75, tw_name: "隆隆石", jp_name: "ゴローン", en_name: "Graveler" },
      { code: :GOLEM, id: 76, tw_name: "隆隆岩", jp_name: "ゴローニャ", en_name: "Golem" },
      { code: :PONYTA, id: 77, tw_name: "小火馬", jp_name: "ポニータ", en_name: "Ponyta" },
      { code: :RAPIDASH, id: 78, tw_name: "烈焰馬", jp_name: "ギャロップ", en_name: "Rapidash" },
      { code: :SLOWPOKE, id: 79, tw_name: "呆呆獸", jp_name: "ヤドン", en_name: "Slowpoke" },
      { code: :SLOWBRO, id: 80, tw_name: "呆海馬", jp_name: "ヤドラン", en_name: "Slowbro" },
      { code: :MAGNEMITE, id: 81, tw_name: "小磁怪", jp_name: "コイル", en_name: "Magnemite" },
      { code: :MAGNETON, id: 82, tw_name: "三合一磁怪", jp_name: "レアコイル", en_name: "Magneton" },
      { code: :FARFETCHD, id: 83, tw_name: "大蔥鴨", jp_name: "カモネギ", en_name: "Farfetch'd" },
      { code: :DODUO, id: 84, tw_name: "嘟嘟", jp_name: "ドードー", en_name: "Doduo" },
      { code: :DODRIO, id: 85, tw_name: "嘟嘟利", jp_name: "ドードリオ", en_name: "Dodrio" },
      { code: :SEEL, id: 86, tw_name: "小海獅", jp_name: "パウワウ", en_name: "Seel" },
      { code: :DEWGONG, id: 87, tw_name: "白海獅", jp_name: "ジュゴン", en_name: "Dewgong" },
      { code: :GRIMER, id: 88, tw_name: "臭泥", jp_name: "ベトベター", en_name: "Grimer" },
      { code: :MUK, id: 89, tw_name: "臭臭泥", jp_name: "ベトベトン", en_name: "Muk" },
      { code: :SHELLDER, id: 90, tw_name: "大舌貝", jp_name: "シェルダー", en_name: "Shellder" },
      { code: :CLOYSTER, id: 91, tw_name: "鐵甲貝", jp_name: "パルシェン", en_name: "Cloyster" },
      { code: :GASTLY, id: 92, tw_name: "鬼斯", jp_name: "ゴース", en_name: "Gastly" },
      { code: :HAUNTER, id: 93, tw_name: "鬼斯通", jp_name: "ゴースト", en_name: "Haunter" },
      { code: :GENGAR, id: 94, tw_name: "耿鬼", jp_name: "ゲンガー", en_name: "Gengar" },
      { code: :ONIX, id: 95, tw_name: "大岩蛇", jp_name: "イワーク", en_name: "Onix" },
      { code: :DROWZEE, id: 96, tw_name: "素利普", jp_name: "スリープ", en_name: "Drowzee" },
      { code: :HYPNO, id: 97, tw_name: "素利柏", jp_name: "スリーパー", en_name: "Hypno" },
      { code: :KRABBY, id: 98, tw_name: "大鉗蟹", jp_name: "クラブ", en_name: "Krabby" },
      { code: :KINGLER, id: 99, tw_name: "巨鉗蟹", jp_name: "キングラー", en_name: "Kingler" },
      { code: :VOLTORB, id: 100, tw_name: "雷電球", jp_name: "ビリリダマ", en_name: "Voltorb" },
      { code: :ELECTRODE, id: 101, tw_name: "頑皮彈", jp_name: "マルマイン", en_name: "Electrode" },
      { code: :EXEGGCUTE, id: 102, tw_name: "蛋蛋", jp_name: "タマタマ", en_name: "Exeggcute" },
      { code: :EXEGGUTOR, id: 103, tw_name: "椰蛋樹", jp_name: "ナッシー", en_name: "Exeggutor" },
      { code: :CUBONE, id: 104, tw_name: "卡拉卡拉", jp_name: "カラカラ", en_name: "Cubone" },
      { code: :MAROWAK, id: 105, tw_name: "嘎啦嘎啦", jp_name: "ガラガラ", en_name: "Marowak" },
      { code: :HITMONLEE, id: 106, tw_name: "沙瓦郎", jp_name: "サワムラー", en_name: "Hitmonlee" },
      { code: :HITMONCHAN, id: 107, tw_name: "艾比郎", jp_name: "エビワラー", en_name: "Hitmonchan" },
      { code: :LICKITUNG, id: 108, tw_name: "大舌頭", jp_name: "ベロリンガ", en_name: "Lickitung" },
      { code: :KOFFING, id: 109, tw_name: "瓦斯彈", jp_name: "ドガース", en_name: "Koffing" },
      { code: :WEEZING, id: 110, tw_name: "雙彈瓦斯", jp_name: "マタドガス", en_name: "Weezing" },
      { code: :RHYHORN, id: 111, tw_name: "獨角犀牛", jp_name: "サイホーン", en_name: "Rhyhorn" },
      { code: :RHYDON, id: 112, tw_name: "鐵甲暴龍", jp_name: "サイドン", en_name: "Rhydon" },
      { code: :CHANSEY, id: 113, tw_name: "吉利蛋", jp_name: "ラッキー", en_name: "Chansey" },
      { code: :TANGELA, id: 114, tw_name: "蔓藤怪", jp_name: "モンジャラ", en_name: "Tangela" },
      { code: :KANGASKHAN, id: 115, tw_name: "袋龍", jp_name: "ガルーラ", en_name: "Kangaskhan" },
      { code: :HORSEA, id: 116, tw_name: "墨海馬", jp_name: "タッツー", en_name: "Horsea" },
      { code: :SEADRA, id: 117, tw_name: "海刺龍", jp_name: "シードラ", en_name: "Seadra" },
      { code: :GOLDEEN, id: 118, tw_name: "角金魚", jp_name: "トサキント", en_name: "Goldeen" },
      { code: :SEAKING, id: 119, tw_name: "金魚王", jp_name: "アズマオウ", en_name: "Seaking" },
      { code: :STARYU, id: 120, tw_name: "海星星", jp_name: "ヒトデマン", en_name: "Staryu" },
      { code: :STARMIE, id: 121, tw_name: "寶石海星", jp_name: "スターミー", en_name: "Starmie" },
      { code: :MR_MIME, id: 122, tw_name: "吸盤魔偶", jp_name: "バリヤード", en_name: "Mr." },
      { code: :SCYTHER, id: 123, tw_name: "飛天螳螂", jp_name: "ストライク", en_name: "Scyther" },
      { code: :JYNX, id: 124, tw_name: "迷唇姐", jp_name: "ルージュラ", en_name: "Jynx" },
      { code: :ELECTABUZZ, id: 125, tw_name: "電擊獸", jp_name: "エレブー", en_name: "Electabuzz" },
      { code: :MAGMAR, id: 126, tw_name: "鴨嘴火獸", jp_name: "ブーバー", en_name: "Magmar" },
      { code: :PINSIR, id: 127, tw_name: "大甲", jp_name: "カイロス", en_name: "Pinsir" },
      { code: :TAUROS, id: 128, tw_name: "肯泰羅", jp_name: "ケンタロス", en_name: "Tauros" },
      { code: :MAGIKARP, id: 129, tw_name: "鯉魚王", jp_name: "コイキング", en_name: "Magikarp" },
      { code: :GYARADOS, id: 130, tw_name: "暴鯉龍", jp_name: "ギャラドス", en_name: "Gyarados" },
      { code: :LAPRAS, id: 131, tw_name: "乘龍", jp_name: "ラプラス", en_name: "Lapras" },
      { code: :DITTO, id: 132, tw_name: "百變怪", jp_name: "メタモン", en_name: "Ditto" },
      { code: :EEVEE, id: 133, tw_name: "伊布", jp_name: "イーブイ", en_name: "Eevee" },
      { code: :VAPOREON, id: 134, tw_name: "水精靈", jp_name: "シャワーズ", en_name: "Vaporeon" },
      { code: :JOLTEON, id: 135, tw_name: "雷精靈", jp_name: "サンダース", en_name: "Jolteon" },
      { code: :FLAREON, id: 136, tw_name: "火精靈", jp_name: "ブースター", en_name: "Flareon" },
      { code: :PORYGON, id: 137, tw_name: "3D龍", jp_name: "ポリゴン", en_name: "Porygon" },
      { code: :OMANYTE, id: 138, tw_name: "菊石獸", jp_name: "オムナイト", en_name: "Omanyte" },
      { code: :OMASTAR, id: 139, tw_name: "多刺菊石獸", jp_name: "オムスター", en_name: "Omastar" },
      { code: :KABUTO, id: 140, tw_name: "化石盔", jp_name: "カブト", en_name: "Kabuto" },
      { code: :KABUTOPS, id: 141, tw_name: "鐮刀盔", jp_name: "カブトプス", en_name: "Kabutops" },
      { code: :AERODACTYL, id: 142, tw_name: "化石翼龍", jp_name: "プテラ", en_name: "Aerodactyl" },
      { code: :SNORLAX, id: 143, tw_name: "卡比獸", jp_name: "カビゴン", en_name: "Snorlax" },
      { code: :ARTICUNO, id: 144, tw_name: "急凍鳥", jp_name: "フリーザー", en_name: "Articuno" },
      { code: :ZAPDOS, id: 145, tw_name: "閃電鳥", jp_name: "サンダー", en_name: "Zapdos" },
      { code: :MOLTRES, id: 146, tw_name: "火焰鳥", jp_name: "ファイヤー", en_name: "Moltres" },
      { code: :DRATINI, id: 147, tw_name: "迷你龍", jp_name: "ミニリュウ", en_name: "Dratini" },
      { code: :DRAGONAIR, id: 148, tw_name: "哈克龍", jp_name: "ハクリュー", en_name: "Dragonair" },
      { code: :DRAGONITE, id: 149, tw_name: "快龍", jp_name: "カイリュー", en_name: "Dragonite" },
      { code: :MEWTWO, id: 150, tw_name: "超夢", jp_name: "ミュウツー", en_name: "Mewtwo" },
      { code: :MEW, id: 151, tw_name: "夢幻", jp_name: "ミュウ", en_name: "Mew" },
    ]
  end
end
